# Sensirion SHT40 sensor
- platform: sht4x
  temperature:
    name: "Sauna Temperature"
    id: sauna_temperature
    on_value:
      - then:
        - lvgl.label.update:
            id: lbl_temp
            text: !lambda |-
              static char buf[10];
              snprintf(buf, sizeof(buf), "%.1f \U000F0504", x);
              return buf;
    # change sleep duration based on sauna temperature
    on_value_range:
        # sleep for 30min below 40deg
        - below: 40.0
          then:
            - lambda: |-
                id(sleep_duration_sec) = 1800;
                id(deep_sleep_default).set_sleep_duration(id(sleep_duration_sec) * 1000);
        # sleep for 20min below 50deg
        - above: 40.0
          below: 50.0
          then:
            - lambda: |-
                id(sleep_duration_sec) = 1200;
                id(deep_sleep_default).set_sleep_duration(id(sleep_duration_sec) * 1000);
        # sleep for 10min below 60deg
        - above: 50.0
          below: 60.0
          then:
            - lambda: |-
                id(sleep_duration_sec) = 600;
                id(deep_sleep_default).set_sleep_duration(id(sleep_duration_sec) * 1000);
        # sleep for 5min below 70deg
        - above: 60.0
          below: 70.0
          then:
            - lambda: |-
                id(sleep_duration_sec) = 300;
                id(deep_sleep_default).set_sleep_duration(id(sleep_duration_sec) * 1000);
        # sleep for 5min below 70deg
        - above: 70.0
          then:
            - lambda: |-
                id(sleep_duration_sec) = 60;
                id(deep_sleep_default).set_sleep_duration(id(sleep_duration_sec) * 1000);
    filters:
      - sliding_window_moving_average:
          window_size: 20
          send_every: 20
  humidity:
    name: "Sauna Relative Humidity"
    on_value:
      - lvgl.label.update:
          id: lbl_hum
          text: !lambda |-
            static char buf[10];
            snprintf(buf, sizeof(buf), "%.1f \U000F03F0", x);
            return buf;
    filters:
      - sliding_window_moving_average:
          window_size: 20
          send_every: 20
  update_interval: 1s
# Temperature delta
- platform: copy
  source_id: sauna_temperature
  name: "Sauna Temperature Delta"
  id: sauna_temperature_delta
  unit_of_measurement: "°C"
  filters:
    - sliding_window_moving_average:
        window_size: 60
        send_every: 60
    - lambda: |-
        auto delta = x - id(last_temp);
        id(last_temp) = x;
        return delta;
# WiFi sensor
- platform: wifi_signal
  name: "Sauna WiFi Signal"
  id: wifi_signal_db
  update_interval: 5s
  entity_category: "diagnostic"
  on_value:
    if:
      condition:
        wifi.connected:
      then:
        - lvgl.label.update:
            id: lbl_diagnostic_wifi_db_value
            text: !lambda |-
              static char buf[10];
              snprintf(buf, sizeof(buf), "%.1f dBm", x);
              return buf;
- platform: copy
  source_id: wifi_signal_db
  name: "Sauna WiFi Signal Percentage"
  filters:
    - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
  unit_of_measurement: "Signal %"
  entity_category: "diagnostic"
  device_class: ""
  on_value:
    if:
      condition:
        wifi.connected:
      then:
        - lvgl.label.update:
            id: lbl_wifi_icon
            text: !lambda |-
              if (x < 20.0) {
                return "\U000F091F"; // mdi-wifi-strength-1
              } else if (x < 40.0) {
                return "\U000F0922"; // mdi-wifi-strength-2
              } else if (x < 60.0) {
                return "\U000F0925"; // mdi-wifi-strength-3
              } else {
                return "\U000F0928"; // mdi-wifi-strength-4
              }
        - lvgl.label.update:
            id: lbl_diagnostic_wifi_percent_value
            text: !lambda |-
              static char buf[10];
              snprintf(buf, sizeof(buf), "%.1f %%", x);
              return buf;
      else:
        - lvgl.label.update:
            id: lbl_wifi_icon
            text: !lambda |-
              return "\U000F092B"; // mdi-wifi-alert
# Outdoor temperature from heat pump
- platform: homeassistant
  id: outside_temperature
  entity_id: sensor.kuutsu_13_outdoor_temperature
  on_value:
    - lvgl.label.update:
        id: lbl_temp_outside
        text: !lambda |-
          static char buf[10];
          snprintf(buf, sizeof(buf), "%.1f \U000F0504", x);
          return buf;
# Battery voltage
- platform: adc
  pin: GPIO04
  name: "Sauna Battery Voltage"
  id: battery_voltage
  entity_category: "diagnostic"
  samples: 10
  attenuation: 12db
  update_interval: 60s
  filters:
    - multiply: 2.0
  on_value:
    - lvgl.label.update:
        id: lbl_diagnostic_battery_voltage_value
        text: !lambda |-
          static char buf[10];
          snprintf(buf, sizeof(buf), "%.1f V", x);
          return buf;
# Battery percentage
- platform: copy
  source_id: battery_voltage
  name: "Sauna Battery Percentage"
  filters:
    - calibrate_linear:
        - 3.0 -> 0.0
        - 4.2 -> 100.0
    - clamp:
        min_value: 0.0
        max_value: 100.0
  unit_of_measurement: "%"
  entity_category: "diagnostic"
  device_class: "battery"
  on_value:
    - lvgl.label.update:
        id: lbl_battery_icon
        text: !lambda |-
          if (x < 10.0) {
            return "\U000F10CD"; // mdi-battery-alert-variant-outline
          } else if (x < 30.0) {
            return "\U000F12A1"; // mdi-battery-low
          } else if (x < 60.0) {
            return "\U000F12A1"; // mdi-battery-medium
          } else {
            return "\U000F12A3"; // mdi-battery-high
          }
    - lvgl.label.update:
        id: lbl_diagnostic_battery_percent_value
        text: !lambda |-
          static char buf[10];
          snprintf(buf, sizeof(buf), "%.1f %%", x);
          return buf;
# ESP32 internal temperature
- platform: internal_temperature
  name: "Sauna ESP32 Internal Temperature"
  on_value:
    - lvgl.label.update:
        id: lbl_diagnostic_internal_temperature_value
        text: !lambda |-
          static char buf[10];
          snprintf(buf, sizeof(buf), "%.1f °C", x);
          return buf;
# Wakeup sensor
- platform: template
  name: "Wakeup Cause"
  id: wakeup_cause
  entity_category: "diagnostic"
  accuracy_decimals: 0
  lambda: return static_cast<float>(esp_sleep_get_wakeup_cause());
# Sleep duration
- platform: template
  name: "Sleep Duration"
  id: sleep_duration_sensor
  entity_category: "diagnostic"
  unit_of_measurement: "s"
  accuracy_decimals: 0
  lambda: return static_cast<float>(id(sleep_duration_sec));
